### ISSUE TITLE
The test to search users with a complex query fails

### ISSUE THREAD

**Issue by dacrome** [osiam/connector4java-integration-tests#216]
The [CompleteUserIT.search_for_user_by_complex_query](https://github.com/osiam/connector4java-integration-tests/blob/master/src/test/java/org/osiam/client/CompleteUserIT.java#L115) fails because a read timeout of the client occurred. Only with postgres and not always. The test search users with all possible attributes set. Maybe this isn't a "real life" scenario and we can split the test into multiple tests to verify that users can be found with every attribute?

**Comment by tkrille** [comment]
Yes, let's write a test case for each single attribute and also some tests that use common combinations of attributes.

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
