### ISSUE TITLE
Cache Docker images

### ISSUE THREAD

**Issue by tkrille** [osiam/connector4java-integration-tests#227]
Currently we have to download all Docker images, like mysql, postgres, tomcat, before the test are run. We should put these images into the build cache of CircleCI, i.e. by exporting them to some folder and then add that folder to the cache.

**Comment by dacrome** [comment]
I guess [this blog post](http://tschottdorf.github.io/cockroach-docker-circleci-continuous-integration/) is a good start in this topic.

**Comment by dacrome** [comment]
Too much work but too little effort. I think we should leave it like it is.
