### ISSUE TITLE
Bring back verification of sent emails

### ISSUE THREAD

**Issue by tkrille** [osiam/connector4java-integration-tests#232]
Running the tests with Docker had the disadvantage that we couldn't retrieve the sent emails (e.g. from the self administration) from Greenmail to verify them. At least this was not possible as easily as before. We should re-activate these tests by connecting to the POP3 interface of Greenmail and get the latest received mail. Does anyone know a simple POP3 client?

**Comment by dacrome** [comment]
We should use java mail to fetch the mails, like I already [tested here](https://github.com/osiam/connector4java-integration-tests/blob/418518dccc807401da3e9fd60912464135faccc1/src/test/groovy/org/osiam/test/integration/ChangeEmailIT.groovy#L116). But for sure this is not how we should use it ;)

**Comment by tkrille** [comment]
lgtm, but leaves room for improvement. Nevertheless, I will search for yet another client.
