### ISSUE TITLE
Documentation for Docker Usage

### ISSUE THREAD

**Issue by sputnik27** [osiam/connector4java-integration-tests#280]
Running the tests requires a Docker configuration that is not obvious in order to let Java communicate with Docker. This should be briefly described in the README.

The error message describing this problem reads like
> [ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.9.2:clean (clean-docker-images) on project integration-tests: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1] failed: Connection refused -> [Help 1]

**Comment by tkrille** [comment]
+1, you wanna do this?

**Comment by dacrome** [comment]
+1
