### ISSUE TITLE
Cross Project Debugging?

### ISSUE THREAD

**Issue by sputnik27** [osiam/connector4java-integration-tests#282]
Hello,

I am working on an issue in the [resource-server](https://github.com/osiam/resource-server/issues/7). I have tests in the connector4java-integration-tests project to show if the bug is fixed. My question is: How can I debug code in the resource-server?

Here is what I tried:
* `mvn clean pre-integration-test` in the IT project
* Run test in the IDE

I want a breakpoint [here](https://github.com/osiam/resource-server/blob/55d17ad8267d5e75454c5f673a8c9ad53b60a036/src/main/java/org/osiam/storage/query/FilterConstraint.java#L43). I was not able to open `FilterConstraint` in the IT project in my IDE. Stepping from the IT does also not seem to be a viable option.

In case this is relevant: I am using IntelliJ Ultimate 14.1.4 and open jdk on Ubuntu vivid, as well as the official Docker (not from the Ubuntu repos).

**Comment by tkrille** [comment]
Hi @sputnik27,

this is the way I do it:

I'm using IntelliJ, too, so I open 2 windows with the integration test project and the service I want to debug. But it's also possible to add multiple modules to IntelliJ or just open the 2 projects in your Eclipse work space.

First, you have to start Tomcat in Debug mode and expose the debug port (`8000`). Edit the file `src/main/docker/tomcat/Dockerfile` and adjust it like this:

```dockerfile
[...]
RUN echo "${user.timezone}" > /etc/timezone

# change this line
EXPOSE 8180 11110 8000

# add this line
CMD [ "catalina.sh", "jpda", "run"]
```

Also change the file `src/main/docker/tomcat/conf.yml` like this:

```yaml
[...]
ports:
  - 8180
  - 11110
  # add this line
  - 8000

healthChecks:
[...]
```

With this changes, Tomcat now starts in debug mode bound on `localhost` port `8000`. Next you have to deactivate the connection timeout of the connector, so you can quietly debug everything. Change the file `src/test/groovy/org/osiam/test/integration/AbstractIT.groovy` like this:

```groovy
[...]
    protected AccessToken accessToken

    static {
        OsiamConnector.setConnectTimeout(-1); // change this line
        OsiamConnector.setReadTimeout(-1); // change this line

        OSIAM_CONNECTOR = new OsiamConnector.Builder()
[...]
```

And change the file `src/test/java/org/osiam/client/AbstractIntegrationTestBase.java` like this:

```java
[...]
    protected static final Client CLIENT = ClientBuilder.newBuilder().register(JacksonFeature.class).build();

    static {
        OsiamConnector.setConnectTimeout(-1); // change this line
        OsiamConnector.setReadTimeout(-1); // change this line

        OSIAM_CONNECTOR = new OsiamConnector.Builder()
[...]
```

Now you're ready to start the IT setup with:

```shell
mvn clean pre-integration-test
```

In your IDE containing the service project you can now attach the debugger. Just use the normal remote debugging setup and connect to `localhost:8000`. Set your breakpoints or whatever and run the test in the ITs project. Your IDE should pop up as soon as the service reaches the breakpoint.

**Comment by tkrille** [comment]
@sputnik27 It would be very nice if you could add this information to the docs. Thanks.

**Comment by sputnik27** [comment]
Thanks a lot, this works for me. I can turn this into documentation, but I would prefer a less 'hacky' solution with a maven profile for debugging.

What do you think about this, @wallner, @dacrome?

**Comment by tkrille** [comment]
+1 for a distinct Maven profile for this. But as a first step (until the profile has been implemented) we should document the current way.

**Comment by dacrome** [comment]
+1 for the maven profile

**Comment by sputnik27** [comment]
Since my question is answered, I will close this issue. Thank you again for your in-depth answer, @tkrille.
